# Generated by Django 4.2.1 on 2023-05-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_category', models.CharField(choices=[('Outfit', 'Outfit'), ('footwear', 'footwear'), ('Cosmetics', 'cosmetics'), ('Electronics', 'Electronics'), ('Kitchen Appliences', 'Kitchen Appliences'), ('Others', 'Others')], max_length=100)),
                ('product_image', models.ImageField(upload_to='pro_image')),
                ('product_description', models.CharField(max_length=100)),
            ],
        ),
    ]
